### ISSUE TITLE
[BUG] Double 'Online' Contacts

### ISSUE THREAD

**Issue by Anime-Machina** [diaspora/jsxc#89] opened 2015-03-02 21:26 UTC
![IMG](http://i.imgur.com/PohRlBk.png)

I thought it was fixed...

Any way just hit F5 to reproduce it ^^

**Comment by jhass** [comment] 2015-03-02 21:29
I can confirm.

**Comment by AugierLe42e** [comment] 2015-03-04 20:52
@Zauberstuhl : I think thi bug is getting really worse :/

![chat](https://cloud.githubusercontent.com/assets/3429231/6493113/cda238e6-c2b8-11e4-99da-8c139a0f3f21.png)

**Comment by Anime-Machina** [comment] 2015-03-04 21:43
It disappears after a little wile like 3 to 5 minutes, I think it has to do with sessions of NGINX...

**Comment by AugierLe42e** [comment] 2015-03-04 21:44
Possible.

**Comment by Flaburgan** [comment] 2015-03-08 21:16
It's not getting worst: it's not "double", it's each time someone is in an aspect you activated the chat for.

**Comment by AugierLe42e** [comment] 2015-03-08 21:18
Nope, it has something to do with reconnection. See on the picture, I have some contacts appearing 5 to six times and nobody being in 6 different aspects (2 maximum).

**Comment by Zauberstuhl** [comment] 2015-03-08 22:16
I fixed the grouping stuff. Now it seams like vines sends double contacts.
Check `jsxc.log`.

I am able to investigate that next weekend.

lgl

**Comment by AugierLe42e** [comment] 2015-03-09 13:32
Ok, I can confirm the bug. Each time I reload the page the contacts appear once and then, after the automatic reconection, each contact appear two times. I guess it is becaus the contats list isn't empty when JSXC refills it. Where am I able to see the logs ?

**Comment by Zauberstuhl** [comment] 2015-03-11 14:53
browser console. check `jsxc.log`

**Comment by Anime-Machina** [comment] 2015-03-16 07:15
Sorry slacked a bit for a wile, this afternoon you'll have your log ^^

**Comment by Nicklas2751** [comment] 2015-06-05 01:02
The bug was in line 276, the time check are wrong. It has to be an '<' instead of an '>'.

**Comment by svbergerem** [comment] 2015-06-07 19:32
The [changelog of jsxc](https://github.com/jsxc/jsxc/releases/tag/v2.0.0-beta1) says for version 2.0.0-beta1

> fix duplicated roster items

so maybe updating our jsxc version will fix this bug.

**Comment by Zauberstuhl** [comment] 2015-06-08 14:53
@svbergerem updating the client is on my radar. it'll be no simple update

> fix duplicated roster items

maybe this one https://github.com/jsxc/jsxc/commit/01b14279b3f22e10983ece7f043d82b5efbc4b9a ?

@Nicklas2751 could you create a pull-request in the upstream repository? The bug you describe still exists (https://github.com/jsxc/jsxc/blob/master/src/jsxc.lib.js#L246). Thanks!

**Comment by Nicklas2751** [comment] 2015-06-08 14:58
@Zauberstuhl There is one already: https://github.com/jsxc/jsxc/pull/182 ;)

**Comment by Zauberstuhl** [comment] 2015-06-08 14:58
just saw your PM :) Cheers!

**Comment by Nicklas2751** [comment] 2015-06-10 09:31
The bug i found was an missunderstand of the comment of "restore". This Bug is fixed in the upstream repository, so if we merge the upstream commits to this repo, the bug shoud be fixed.

**Comment by Zauberstuhl** [comment] 2015-06-10 13:42
thanks for your effort anyway!

**Comment by Zauberstuhl** [comment] 2015-08-19 07:22
cannot reproduce it with [v0.1.2](https://github.com/diaspora/jsxc/issues?q=milestone%3A0.1.2)

can someone confirm this?

**Comment by Zauberstuhl** [comment] 2015-08-20 11:39
Closing this. The refresh-bug is gone and the duplicates related to multiple groups is related to vines (see diaspora/vines#61)

**Closed by Zauberstuhl** 2015-08-20 11:39 UTC
Labels: bug
