### ISSUE TITLE
#jsxc_roster element is hidden with chat enabled

### ISSUE THREAD

**Issue by axilleas** [diaspora/jsxc#141] opened 2015-11-30 11:37 UTC
Following https://librenet.gr/posts/490484 I cannot see the chat window because `#jsxc_roster` element has a `right: -204px;` attribute. Disabling it makes the chat arrow appear.

**Comment by comzeradd** [comment] 2015-11-30 12:46
The problem seems to be that the chat is initiated with an option to "relogin" and at this time its container is smaller dragging the `#jsxc_toggleRoster` more into the right than it should be. If you choose to login in the chat the container (which now displays the roster) is wider pushing the toggle to right place.

**Comment by Zauberstuhl** [comment] 2015-11-30 13:56
hi guys, a lot happened in dev branch since the last alpha release.

I just tested version 0.1.4 on my dev setup and sechat.org.
checkout my PR for stable branch https://github.com/diaspora/diaspora/pull/6569

I am confident that the problem is gone with the latest jsxc version.

Cheers,
Lukas

**Comment by Zauberstuhl** [comment] 2015-12-02 23:38
closing this! was fixed at least with the newest version

**Closed by Zauberstuhl** 2015-12-02 23:38 UTC
