### ISSUE TITLE
"Hide offline contacts" only hides profile picture

### ISSUE THREAD

**Issue by prellele** [diaspora/jsxc#153] opened 2016-04-12 10:42 UTC
Hitting the "Hide offline contacts" button in the chatsidebar only has the consequence that "profile pictures"/"colorfull chars" of offline contacts are hidden

moved from https://github.com/diaspora/diaspora/issues/6756

**Comment by Zauberstuhl** [comment] 2016-04-12 21:38
duplicate of #144

**Closed by Zauberstuhl** 2016-04-12 21:38 UTC
